export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';
export const FETCH_SINGLE_PRODUCT_SUCCESS = 'FETCH_SINGLE_PRODUCT_SUCCESS';
export const FETCH_SINGLE_PRODUCT_FAIL = 'FETCH_SINGLE_PRODUCT_FAIL';

export const ADD_SINGLE_PRODUCT = 'ADD_SINGLE_PRODUCT';
export const ADD_SINGLE_PRODUCT_SUCCESS = 'ADD_SINGLE_PRODUCT_SUCCESS';
export const ADD_SINGLE_PRODUCT_FAIL = 'ADD_SINGLE_PRODUCT_FAIL';

export const UPDATE_SINGLE_PRODUCT = 'UPDATE_SINGLE_PRODUCT';
export const UPDATE_SINGLE_PRODUCT_SUCCESS = 'UPDATE_SINGLE_PRODUCT_SUCCESS';
export const UPDATE_SINGLE_PRODUCT_FAIL = 'UPDATE_SINGLE_PRODUCT_FAIL';

export const DELETE_SINGLE_PRODUCT = 'DELETE_SINGLE_PRODUCT';
export const DELETE_SINGLE_PRODUCT_SUCCESS = 'DELETE_SINGLE_PRODUCT_SUCCESS';
export const DELETE_SINGLE_PRODUCT_FAIL = 'DELETE_SINGLE_PRODUCT_FAIL';

export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const CLEAR_CRUD_ERROR = 'CLEAR_CRUD_ERROR';
